### ISSUE TITLE
Build File

### ISSUE THREAD

**Issue by toastynerd** [austinhinderer/Player#2]
https://github.com/austinhinderer/Player/pull/1 pulls out the different object logic into separate files to make them easier to work with but it would nice to have a single that could be included into the browser. I propose a grunt file with a build process to essentially concat them all into single file. This would also make it easy to build a minified/uglified version.

**Comment by swansong** [comment]
Pull request open with requested feature. Added some unused framework for handling less, but not sure if we're going that route. Also added JSHint and Watch to grunt for you while editing files.

**Comment by swansong** [comment]
Going to look into adding source maps for minified css and js and adding in compass+scss to make the css for us.
