### ISSUE TITLE
Add JSHint or JSLint (or neither)

### ISSUE THREAD

**Issue by swansong** [austinhinderer/Player#42]
We can add a linter to the grunt config easily, but do we want one and if so which one?

**Comment by austinhinderer** [comment]
I prefer JSHint.

**Comment by swansong** [comment]
?Me too. Rock it?


Jonathan Swanson
Web Developer
University Marketing and Communications
________________________________

**Comment by austinhinderer** [comment]
Hell yeah

**Comment by austinhinderer** [comment]
Added
